on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:

  component-analysis-npm-audit:
      name: Component Analysis and NPM Audit
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3.6.0
          with:
            node-version: '14'

        - run: npm install --package-lock
        - run: npm audit fix

        - name: Run NPM Audit
          run: npm audit --json > npm-audit.json
          continue-on-error: true

        - name: Upload NPM Audit Report
          uses: actions/upload-artifact@v3
          with:
            name: npm-audit-report
            path: npm-audit.json

  build-dummy:
    name: Build Echo statment
    runs-on: ubuntu-latest
    
    steps:

    - name: Echo building going on 
      run: "echo building going on"


  deploy-dummy:
    name: deploy echo statment
    runs-on: ubuntu-latest
    needs: build-dummy
    
    steps:

    - name: echo deploying going on 
      run: "echo deploying going on"

  
    - name: Bandit check
      uses: jpetrucciani/bandit-check@main
      with:
        path: '.'
        bandit_flags: '-o audit-bandit.json -f json'
