on:
  push:
    branches:
      - main
  workflow_dispatch: 


jobs:
  build-dummy:
    name: Build Echo statment
    runs-on: ubuntu-latest
    
    steps:

    - name: Echo building going on 
      run: "echo building going on"


  deploy-dummy:
    name: deploy echo statment
    runs-on: ubuntu-latest
    needs: build-dummy
    
    steps:

    - name: echo deploying going on 
      run: "echo deploying going on"
       